# -*- coding: utf-8 -*-
"""Trabalho Visualização de dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_KgdYzuIacF6aRbb1hNzb7whqjhv43RI
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as colors
import seaborn as sns
import datetime
import numpy as np
uri = "https://raw.githubusercontent.com/macguilck/macguilck/main/obitos_mg_covid_19(mar-20_jul_20).csv"
df = pd.read_csv(uri, encoding='ISO-8859-1', engine='python', sep=';', index_col=None)
df.head()

x = df.MES_OBITO
y = df.QTD_MES

x1 = df.HOMEM
y1 = df.MULHER
plt.plot(x, x1, label='Homens')
plt.plot(x, y1, label='Mulheres')
plt.title('NÚMERO DE MORTES POR MÊS POR GÊNERO')
plt.legend()
#plt.scatter(x1, y1, color='b')
plt.ylabel('QTDE DE MORTES');

x3 = df.HOMEM.sum(), df.MULHER.sum()
label = ['Homem', 'Mulher']
plt.pie(x3, 
        radius=1, 
        labels = label,
        autopct='%.f'
        )
plt.title('TOTAL DE MORTES');

#plt.bar(x, y, 
#        width=1, 
#        edgecolor="white", 
#       linewidth=0.7)
fig, ax = plt.subplots()
sns.barplot(x, y, data=df, palette='RdPu')
ax.set_ylabel('Quantidades', fontdict={'fontsize':14})
ax.set_title('NÚMERO TOTAL DE MORTES POR MÊS');